language: python
os:
  - linux
  - freebsd
# ===== Linux ======
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3
jobs:
  exclude:
    - os: freebsd
      python: pypy3
  include:
    - os: linux
      dist: bionic
      python: 3.6
    - os: linux
      dist: bionic
      python: 3.7
    - os: linux
      dist: bionic
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.9
    - os: linux
      dist: bionic
      python: pypy3
    # ======= OSX ========
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
      script: python3 -m pytest
    - name: "Python 3.8.6 on macOS 10.15"
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
      script: python3 -m pytest
    - name: "Python 3.9.5 on macOS 11.3"
      os: osx
      osx_image: xcode12.5
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
      script: python3 -m pytest
    #  ====== WINDOWS =========
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.10 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.10
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.9.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.9.5
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
install: pip install -r requirements.txt && pip install .
script: python -m pytest
after_success:
  bash <(curl -s https://codecov.io/bash)
