language: python
os:
    - linux
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"
install:
    pip install -r requirements.txt && pip install .
script:
    make test
after_success:
    bash <(curl -s https://codecov.io/bash)
